# Generated by Django 5.0.1 on 2024-02-03 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number in the format XXXXXXXXXX.', regex='^\\d{10}$')])),
                ('aadhaar', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar_number', message='Enter a valid aadhaar number in the format XXXX XXXX XXXX.', regex='^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$')])),
                ('gstin', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_gstin', message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('address_line_3', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Enter a valid pincode in the format XXXXXX.', regex='^[1-9]{1}[0-9]{2}\\\\s{0, 1}[0-9]{3}$')])),
                ('additional_contact', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
