# Generated by Django 5.0.1 on 2024-02-03 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='aadhaar',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar_number', message='Enter a valid aadhaar number in the format XXXX XXXX XXXX.', regex='^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$')]),
        ),
    ]
