# Generated by Django 5.0.1 on 2024-02-03 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_seller_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pincode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Enter a valid pincode in the format XXXXXX.', regex='^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$')]),
        ),
    ]
