# Generated by Django 5.0.1 on 2024-02-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
