# Generated by Django 5.0.1 on 2024-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_product_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(related_name='attribute', to='catalogue.category')),
                ('sub_category', models.ManyToManyField(related_name='attribute', to='catalogue.subcategory')),
                ('variant', models.ManyToManyField(related_name='attribute', to='catalogue.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
