# Generated by Django 5.0.1 on 2024-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_attribute_sub_category_alter_attribute_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalogue.subcategory'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='variant',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalogue.variant'),
        ),
    ]
