# Generated by Django 5.0.1 on 2024-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='completeness_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compliance_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='correctness_score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
