# Generated by Django 5.0.1 on 2024-02-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalogue.attribute'),
        ),
    ]
