# Generated by Django 5.0.1 on 2024-02-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_rule_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalogue.attribute'),
        ),
    ]
