# Generated by Django 5.0.1 on 2024-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_attribute_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalogue.category'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalogue.subcategory'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='variant',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalogue.variant'),
        ),
    ]
