# Generated by Django 5.0.1 on 2024-02-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_attribute_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='attribute',
        ),
        migrations.AddField(
            model_name='rule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rules/'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='catalogue.category'),
        ),
    ]
