# Generated by Django 5.0.1 on 2024-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_remove_rule_category_remove_rule_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='rules', to='catalogue.category'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='rules', to='catalogue.subcategory'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='variant',
            field=models.ManyToManyField(blank=True, related_name='rules', to='catalogue.variant'),
        ),
    ]
