# Generated by Django 5.0.1 on 2024-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_alter_rule_category_alter_rule_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
