# Generated by Django 5.0.1 on 2024-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_rule_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
