# Generated by Django 5.0.1 on 2024-02-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_alter_rule_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_okay", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("gcp_data", models.JSONField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_logs",
                        to="catalogue.productattribute",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_logs",
                        to="catalogue.image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_logs",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
