# Generated by Django 5.0.1 on 2024-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_alter_rule_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaiable_stock',
            new_name='available_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
