# Generated by Django 5.0.1 on 2024-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_rename_avaiable_stock_product_available_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='GOI', max_length=255),
            preserve_default=False,
        ),
    ]
