# Generated by Django 5.0.1 on 2024-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scoring_status',
            field=models.CharField(choices=[('Uninitialized', 'Uninitialized'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Published', 'Published')], default='Uninitialized', max_length=20),
        ),
    ]
