# Generated by Django 5.0.1 on 2024-02-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_productlog'),
        ('catalogue', '0025_product_scoring_status'),
    ]

    operations = [
    ]
